### ISSUE TITLE
BelongsToTenant not working on user model

### ISSUE THREAD

**Issue by obrunsmann** [HipsterJazzbo/Landlord#45] opened 2016-11-02 23:12 UTC
Hey Guys,

everything works fine: If I query with `Model::find(123)` on my model and the resource does not belong to the current tenant (set via middleware) the request fails.

But: If I query on the User model it does not work. While asking for `User::all()` I get really all results including other customers and while querying `User::findOrFail()` with an ID which does not belong to the current tenant I get the result .. so everytime working with my user model I have to check if `$model->tenant_id == $request->user()->tenant_id`

**Comment by flofloflo** [comment] 2016-11-28 13:52
I'm having the same problem since upgrading Laravel from 5.2 to 5.3 and switching to Landlord v2 at the same time.
Did someone already find out why this happens?

**Comment by HipsterJazzbo** [comment] 2016-11-29 22:39
Does your `User` model `use BelongsToTenants`?

**Comment by flofloflo** [comment] 2016-11-30 08:52
Yes, it does. 
When I use another model which uses the same table everything works as expected. 

The difference is that the `User` model `extends Illuminate\Foundation\Auth\User` while my other model `extends Illuminate\Database\Eloquent\Model`. 
Maybe something from the Laravel Authentication collides with Landlord?

**Comment by obrunsmann** [comment] 2016-11-30 08:53
Yes, same to me. Trait in my User model nevertheless not working.

*Oliver Brunsmann*
Geschäftsführer

*t.* 05481 87500 11
*e.* brunsmann@lefamed.de
*w.* www.lefamed.de
[image: LEFAMED Development GmbH] <https://www.lefamed.de>

*LEFAMED Development GmbH*
Ringeler Str. 127
49525 Lengerich

Amtsgericht Steinfurt
HRB 10677
Geschäftsführer: Oliver Brunsmann

Diese Mail enthält vertrauliche und rechtlich geschützte Informationen.
Wenn Sie nicht der richtige Adressat sind und diese Mail irrtümlich
erhalten haben, informieren Sie bitte sofort den Absender und vernichten
Sie diese Mail.

[image: Aktuell können Sie einige Informationen nicht sehen. Bitte
aktivieren Sie externe Inhalte, um die Mail vollständig angezeigt zu
bekommen.]
<http://www.app.mailtastic.de/api/li/9f4bcbc1-f87f-48cd-a027-8083906e94b9>

2016-11-30 9:52 GMT+01:00 Florian <notifications@github.com>:

**Comment by HipsterJazzbo** [comment] 2016-11-30 20:45
Hmm that's really strange. All the trait does is register some global scopes. Is anyone able to provide a test case for me? I can't replicate.

**Comment by flofloflo** [comment] 2016-12-01 22:41
I'll try to create a test setup tomorrow, thanks for the support!

**Comment by flofloflo** [comment] 2016-12-02 21:48
Maybe I have found out what is happening:
In my app I use `Landlord::addTenant('tenant_id', Auth::user()->tenant_id);` inside of a middleware to add the scope. 

When I call the middleware with `$middleware` as global middleware no scope is applied and (by creating some debug points in the middleware) you can find out that `Auth::user()` is empty.
This happens because of a change in Laravel 5.3 (see: https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0)

> In previous versions of Laravel, you could access session variables or the authenticated user in your controller's constructor. This was never intended to be an explicit feature of the framework. In Laravel 5.3, you can't access the session or authenticated user in your controller's constructor because the middleware has not run yet.

If the scope is applied later by using a group middleware (via `$middlewareGroups`), `Auth::user()` contains the authenticated user. The interesting part here is that in this case the scope is only applied to the "non-user" model. I guess the reason is that the `User` model has already booted when the scope is being applied (as described in #46 ).

So I think the problem is a combination of the changed behavior in Laravel 5.3 and the issue described in #46. 

Does someone know a way to access the authenticated user in the global middleware? This would avoid the "booting-problem" I think.

**Comment by dschniepp** [comment] 2016-12-06 14:25
Did you try to use Landlord v1.0.2?

**Comment by flofloflo** [comment] 2016-12-13 10:29
Unfortunately only with Laravel 5.2 before the upgrade. In this setup everything worked fine.

**Comment by MrRio** [comment] 2016-12-27 18:18
I'm having the same issue, anyone got a resolution?

**Comment by r3donnx** [comment] 2017-01-09 17:00
Code provided by @mariomka https://github.com/HipsterJazzbo/Landlord/issues/49#issuecomment-269249778 somehow fixed this issue for me. Now it works on User model. :)

**Comment by gustavobissolli** [comment] 2017-01-20 17:37
Anyone has found other solution?

**Comment by HipsterJazzbo** [comment] 2017-01-25 01:02
If anyone can work out the actual reason that @mariomka's solution works, we can try to tackle this once and for all.

**Comment by flofloflo** [comment] 2017-01-29 16:46
I can confirm that the solution from [#49](https://github.com/HipsterJazzbo/Landlord/issues/49#issuecomment-269249778) also works for me.

@gustavobissolli Currently I use a workaround in my project, so that I can use the unmodified Landlord release. I have created a second `User` model (named `Employee`) which utilizes the same table but doesn't have the scoping problems, because it isn't used for authentication.

I have created a demo project which shows how the scope changes dependent on the login state.
Maybe this could also help someone to find a way to solve the problem. You can find the project under:
[https://github.com/flofloflo/laravel-landlord-test/tree/landlord-issue-45](https://github.com/flofloflo/laravel-landlord-test/tree/landlord-issue-45)

**Comment by EmadAdly** [comment] 2017-01-30 15:15
@flofloflo You mean that the summary of your solution is that clones the user model to Employee model. Taking into consideration `extends Model` not `extends Authenticatable`
If you mean that, I think it's a good solution :+1:

**Comment by flofloflo** [comment] 2017-01-30 22:21
@EmadAdly Yes, that's the solution (or workaround) I'm currently using. 

The repository I posted shows the difference between using `Model` and `Authenticatable`. It also shows the behaviour of the `Authenticatable`-Model when the user is logged out (everything works, because the `User`-Model isn't booted).

**Comment by jpmurray** [comment] 2017-01-31 03:24
Ok, so I'm using this package in a project, and it's the first time I ever get to use it. Trying to figure out if this could be related.

- I can register users just fine with the auth models provided with Laravel out of the box.
- If I try to call `$user = User::allTenants();` , I'm getting:

```
FatalThrowableError in BelongsToTenants.php line 69:
Call to a member function newQueryWithoutTenants() on null
```

Duplicating into a new model, without `authenticable` does exactly the same.

Would this be the same case, or should I rase a new issue?

**Comment by lasseal** [comment] 2017-02-12 09:42
I can scope the User model by adding `Landlord::addTenant('tenant_id')` to `RouteServiceProvider`'s `boot()` method, but can't get the `tenant_id` off the currently authenticated user, so another solution would be to get the `tenant_id` off the subdomain like `tenant.example.com` instead of the user.

**Comment by lasseal** [comment] 2017-03-03 23:56
Did not work out after all. Any solution to this which doesn't involve cloning the User model?

**Comment by patroniton** [comment] 2017-03-06 20:15
This is also happening for me.

The code from  @mariomka [#49](https://github.com/HipsterJazzbo/Landlord/issues/49#issuecomment-269249778) is also working for me.

@lasseal I managed to use your example to get my User model scoping using the subdomain of the url. What didn't work out for you on your end?

**Comment by lasseal** [comment] 2017-03-06 20:23
@patroniton I was accidentally still checkin the DB for the `tenant_id`, instead of of the subdomain, which I didn't realise before now, doh.

**Comment by HipsterJazzbo** [comment] 2017-05-25 22:40
Has anyone been able to work out way doing a single scope instead of multiple soccer makes a difference?

**Comment by HipsterJazzbo** [comment] 2017-05-25 23:12
I certain there are multiple issues here. I do want to get to the bottom of it, but this thread has gotten too confused.

I'm going to close this issue, but if anyone is still having any of these issues:

- Can't scope the user model
- Landlord not working from global middleware
- Anything that is solved by [that one hack](https://github.com/HipsterJazzbo/Landlord/issues/49#issuecomment-269249778)

Please open a new issue with details about exactly where you are calling `addTenant()` (e.g., the whole middleware, or whatever)

Thanks!

**Closed by HipsterJazzbo** 2017-05-25 23:12 UTC
